feature-flags:
  features:
    experimental-stage-endpoint:
      enabled: true
    development-stage-endpoint:
      enabled: false
    enable-class-level-feature:
      enabled: true
    disable-class-level-feature:
      enabled: false
    conditional-feature:
      enabled: true
  response:
    type: json
